services:
  redis:
    image: redis:7
    container_name: orion-redis
    restart: always

  backend:
    build: ./server
    working_dir: /app
    command: ["node", "build/server.js"]
    environment:
      - REDIS_URL=redis://orion-redis:6379
    depends_on:
      - redis
    ports:
      - "8080:8080"
    restart: always

  worker:
    build: ./server
    working_dir: /app
    command: ["node", "build/worker/worker.js"]
    environment:
      - REDIS_URL=redis://orion-redis:6379
    depends_on:
      - redis
    restart: always

  frontend:
    build: ./client
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    restart: always